### ISSUE TITLE
mono_tum exe hangs，could you please share you test image dataset? Thank you  a lot!

### ISSUE THREAD

**Issue by newforrestgump001** [udaysankar01/xfeatSLAM#6]
./examples/Monocular/mono_tum Vocabulary/ORBvoc.txt examples/Monocular/TUM-VI.yaml img1_spreadannotation2_save_box_img
mono_tum exe hangs，could you share your test image dataset?

**Comment by udaysankar01** [comment]
Hi! I tested mono_tum on the TUM RGB-D dataset. If you load just the images in the dataset, you can get it running with Monocular SLAM. 

You can download the dataset from this TUM RGB-D page: https://cvg.cit.tum.de/data/datasets/rgbd-dataset/download

If you structure the command like this, it should be working.
```
./examples/Monocular/mono_tum Vocabulary/ORBvoc.txt \
                              examples/Monocular/TUM3.yaml \
                              {data_parent_dir}/rgbd_dataset_freiburg2_xyz 
```

Also try testing the code on ORB features to check if it is an issue with XFeat. You can do that with the environment variable `USE_ORB=1`. Please let me know if this works for you.

**Comment by newforrestgump001** [comment]
It works well, thank you a lot!
